[project]
name = "diplomadopyversion1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mplfinance>=0.12.10b0",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "rich>=14.0.0",
]

[tool.ruff]
line-length = 79
